branch-defaults:
  master:
    environment: study-sync-dev
    group_suffix: null
environment-defaults:
  study-sync-dev:
    branch: master
    repository: codecommit
global:
  application_name: study-sync
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js 10 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: codecommit
  sc: git
  workspace_type: Application
